name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and Test
        run: |
           chmod +x gradlew
           ./gradlew shadowJar
           ls -R
           
      - uses: actions/upload-artifact@v1
        with:
          name: sportstracker
          path: build/libs
           
      - name: Publish artefacts
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/libs/sportstracker-0.0.1-SNAPSHOT-all.jar'
          asset_name: 'chef-helper.jar'
          tag: ${{ github.ref }}
          overwrite: true  
